### ISSUE TITLE
AttributeError when running

### ISSUE THREAD

**Issue by ncul777** [mauricelambert/LocalResolver#1]
Python 3.9 in a virtual env
`
Collecting LocalResolver
  Downloading LocalResolver-0.0.1.tar.gz (16 kB)
  Preparing metadata (setup.py) ... done
Collecting scapy
  Downloading scapy-2.5.0.tar.gz (1.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 6.6 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Using legacy 'setup.py install' for LocalResolver, since package 'wheel' is not installed.
Using legacy 'setup.py install' for scapy, since package 'wheel' is not installed.
Installing collected packages: scapy, LocalResolver
  Running setup.py install for scapy ... done
  Running setup.py install for LocalResolver ... done
Successfully installed LocalResolver-0.0.1 scapy-2.5.0
`

The command line tool also produces a similar error
`
from LocalResolver import LocalResolver

localResolver = LocalResolver("192.168.0.2", timeout=3)
hostname_nb = localResolver.resolve_NBTNS()
hostname_ll = localResolver.resolve_LLMNR()
print(hostname_nb, hostname_ll)
`

`
Traceback (most recent call last):
  File "/Users/ncully/Documents/tutorials/network-discovery/resolver.py", line 4, in <module>
    hostname_nb = localResolver.resolve_NBTNS()
  File "/Users/ncully/.pyenv/versions/venv-discovery/lib/python3.9/site-packages/LocalResolver/NetbiosResolver.py", line 51, in resolve_NBTNS
    / NBNSQueryRequest(
  File "/Users/ncully/.pyenv/versions/venv-discovery/lib/python3.9/site-packages/scapy/base_classes.py", line 399, in __call__
    i.__init__(*args, **kargs)
  File "/Users/ncully/.pyenv/versions/venv-discovery/lib/python3.9/site-packages/scapy/packet.py", line 188, in __init__
    raise AttributeError(fname)
AttributeError: FLAGS`

**Comment by mauricelambert** [comment]
Thanks for opening this issue. Scapy API have changed, i fix it.
